version: "3"
services:
  moments:
    build: .
    restart: unless-stopped
    volumes:
      - ./storage:/moments/storage
      - ./cache:/moments/cache
      - ./frontend:/moments/frontend
    command: moments --secret rohow2025
    ports:
      - "3000:3000"
